### ISSUE TITLE
There is a race condition

### ISSUE THREAD

**Issue by SoreGums** [mxgrn/pairs.one#3] opened 2016-09-29 06:33 UTC
When using a touch device or can click tile 2 & a third tile quickly, steal the next players 1 of 2 tile turns.

Like this:

1. start game
2. player 1's turn
3. reveal tile 1
4. reveal tile 2
5. quickly click a 3rd tile (needs to be quicker than the returned response of revealing tile 2)

Tile 1 & Tile 2 turn back over and the 3rd tile is revealed, Player 2's turn, they can only turn over 1 tile, then play returns to Player 1.

somehow the game needs to know that 2 tiles have been revealed and not to reveal the 3rd title.

I'm not sure where to look at this - would make a good blog post or dailydrip video I reckon - fun game :)

**Comment by mxgrn** [comment] 2016-09-30 16:23
Thanks! Hm, this is pretty strange, as the frontend doesn't wait for the response, it updates the game state immediately after the 2nd tile is flipped. So, it shouldn't at all be possible to flip 3 tiles, no matter what. There must be something else going on here, but I can't reproduce the problem. If you find any other factors that may cause this - please, let me know. Until then closing the issue, as I can't seem to be able to do anything about it. Will keep an eye on it though!

**Comment by tiagobarreto** [comment] 2016-09-30 17:02
@SoreGums I also could not reproduce the problem.

**Comment by SoreGums** [comment] 2016-10-01 03:04
It's funny I opened this issue on memory, then I thought let me check and first attempt I got it. Then I wanted to reproduce it again and could even after 4 more rounds...
I'll see if I can hook up the remote debug to chrome on my Android devices as it is easier to click quickly with the finger vs mouse (though it does happen with the mouse too as my wife plays on laptop with the track pad and has done it to me a couple of times)

**Comment by mxgrn** [comment] 2016-10-01 05:22
My new guess is that my Elm code at some point just isn't quick enough to update the DOM before you tap the 3rd tile - too much might be happening before updating the model, especially on bigger boards (on which it should be easier to reproduce that). Will try to verify.

**Comment by mxgrn** [comment] 2016-10-01 05:52
I finally could reproduce some inconsistency in the game state by inserting time-consuming dummy calculations into the handler that processes tile clicks/taps. It's exactly what you described: one player is able, eventually, to flip a tile for another. Will try to debug.

**Comment by SoreGums** [comment] 2016-10-01 06:27
Ok, that's why it happened on my wife's laptop then with the Trackpad and I couldn't reproduce on my beast of a gaming laptop with 48GB RAM and various RAM disks/caches. It is hp stream, super under powered with 2GB of Ram and struggles once you have 3 different tabs open in chrome, actually found the benchmark http://www.userbenchmark.com/UserRun/1217157 ... 

Also I did mean "any response" client/server from revealing tile 2. If there was a msg of "tile 2 revealed" and that was set as soon as tile 2 event fired then tile 3 wouldn't have a chance to to be flipped because rules, "reveal 2 tiles per turn".

Cool that you found it ;)

**Closed** 2016-10-01 06:40 UTC

**Comment by mxgrn** [comment] 2016-10-01 06:43
@SoreGums Thanks for helping me (hopefully) fix this! An update is on its way to production 🎉

**Comment by mxgrn** [comment] 2016-10-06 07:54
@SoreGums I just got a report about a seemingly similar issue :( Have you ever encountered this bug since I "fixed" it? Thx!

**Comment by SoreGums** [comment] 2016-10-06 08:37
Not yet, only played 12 games though, and we both played on fast touch devices, so would have been tricky to hit it.

**Comment by mxgrn** [comment] 2016-10-06 08:46
@SoreGums Cool, thanks. Don't hesitate to ping me if you encounter this.
